'use client';

import { FormEvent, useState } from 'react';

type Analysis = { title: string; description: string; features: string[]; hook: string; benefit: string; cta: string; };
type Scene = { order:number; duration:number; purpose:string; narration:string; visual:string; onScreenText:string };
type Brief = { angle:string; audience:string; hook:string; script:string; cta:string; scenes:Scene[] };
type PlanScene = Scene & { id:string; characterStyle:string; characterAction?:string };
type Plan = { width:number; height:number; totalDuration:number; scenes:PlanScene[] };
type Job = { id:string; status:string; progress:number; duration:number; width:number; height:number };

export default function Home(){
 const [url,setUrl]=useState(''); const [format,setFormat]=useState('vertical'); const [template,setTemplate]=useState('product-launch'); const [status,setStatus]=useState('');
 const [analysis,setAnalysis]=useState<Analysis|null>(null); const [brief,setBrief]=useState<Brief|null>(null); const [plan,setPlan]=useState<Plan|null>(null); const [job,setJob]=useState<Job|null>(null);
 async function analyze(e:FormEvent){e.preventDefault();if(!url.trim())return;setAnalysis(null);setBrief(null);setPlan(null);setJob(null);setStatus('Scraping and analyzing your project…');try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const d=await r.json();if(!r.ok)throw Error(d.error||'Analysis failed');setAnalysis(d.analysis);setStatus('Analysis complete.');}catch(e){setStatus(e instanceof Error?e.message:'Analysis failed.');}}
 async function generateCreative(){if(!analysis)return;setStatus('Building marketing angle, script and storyboard…');try{const r=await fetch('/api/creative',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({analysis,format,template})});const d=await r.json();if(!r.ok)throw Error(d.error||'Creative generation failed');setBrief(d.brief);setStatus('Creative brief ready.');}catch(e){setStatus(e instanceof Error?e.message:'Creative generation failed.');}}
 async function assemble(){if(!brief)return;setStatus('Preparing scenes and character animation directions…');try{const r=await fetch('/api/video-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({format,template,scenes:brief.scenes})});const d=await r.json();if(!r.ok)throw Error(d.error||'Assembly failed');setPlan(d.plan);setStatus('Video assembly ready.');}catch(e){setStatus(e instanceof Error?e.message:'Assembly failed.');}}
 async function render(){if(!plan)return;setStatus('Queueing render job…');try{const r=await fetch('/api/render',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({videoPlan:plan,format,template})});const d=await r.json();if(!r.ok)throw Error(d.error||'Render queue failed');setJob(d.job);setStatus('Render job queued.');}catch(e){setStatus(e instanceof Error?e.message:'Render queue failed.');}}
 return <main className="page"><nav className="nav"><div className="logo">LaunchFrame <span>AI</span></div><div className="badge">MVP • URL → VIDEO</div></nav><section className="hero"><div className="eyebrow">Turn projects into launch content</div><h1>Paste a project.<br/>Get a promo video.</h1><p>LaunchFrame analyzes your website, writes the creative, plans the scenes and prepares an asynchronous video render.</p>
 <form className="card" onSubmit={analyze}><label className="label">Project URL</label><div className="row"><input className="input" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://yourproject.com" type="url" required/><button className="primary" disabled={!url.trim()}>Analyze project</button></div>
 <div className="upload">📸 Optional screenshots — visual upload/storage is next.</div><div className="controls"><select className="select" value={template} onChange={e=>setTemplate(e.target.value)}><option value="product-launch">Product Launch</option><option value="saas-demo">SaaS Demo</option><option value="ai-product">AI Product</option><option value="mobile-app">Mobile App</option></select><select className="select" value={format} onChange={e=>setFormat(e.target.value)}><option value="vertical">Vertical · 9:16</option><option value="horizontal">Horizontal · 16:9</option><option value="square">Square · 1:1</option></select></div>
 {status&&<div className="status">{status}</div>}{analysis&&<div className="results"><div className="panel"><h3>{analysis.title}</h3><p>{analysis.description}</p><ul>{analysis.features.map((f,i)=><li key={i}>{f}</li>)}</ul></div><div className="panel"><h3>Project signals</h3><p><strong>Hook:</strong> {analysis.hook}</p><p><strong>Benefit:</strong> {analysis.benefit}</p><p><strong>CTA:</strong> {analysis.cta}</p></div></div>}
 {analysis&&!brief&&<button type="button" className="primary full" onClick={generateCreative}>Generate script & storyboard →</button>}{brief&&<div className="creative"><div className="panel"><h3>Marketing angle</h3><p>{brief.angle}</p><p><strong>Audience:</strong> {brief.audience}</p><p><strong>Hook:</strong> {brief.hook}</p></div><div className="panel"><h3>Voiceover script</h3><p>{brief.script}</p><p><strong>CTA:</strong> {brief.cta}</p></div><div className="panel storyboard"><h3>Storyboard · {brief.scenes.length} scenes</h3>{brief.scenes.map(s=><div className="scene" key={s.order}><div><strong>Scene {s.order}</strong> · {s.duration}s · {s.purpose}</div><p>{s.narration}</p><small>Visual: {s.visual}</small><small>On-screen: {s.onScreenText}</small></div>)}</div><button type="button" className="primary full" onClick={assemble}>Assemble video scenes →</button></div>}
 {plan&&<div className="creative"><div className="panel"><h3>Assembly ready</h3><p>{plan.width} × {plan.height} · {plan.totalDuration}s · {template}</p><p>Stick characters are inserted only where they improve the explanation.</p></div><div className="panel storyboard"><h3>Character direction</h3>{plan.scenes.map(s=><div className="scene" key={s.id}><strong>Scene {s.order}</strong><p>{s.characterStyle==='stick'?`Stick character: ${s.characterAction}`:'Product visual only'}</p></div>)}</div><button type="button" className="primary full" onClick={render}>Render video →</button></div>}
 {job&&<div className="panel" style={{marginTop:18}}><h3>Render job</h3><p><strong>{job.status}</strong> · {job.width} × {job.height} · {job.duration}s</p><div className="status">Progress: {job.progress}%</div><p className="footer">The render endpoint is now worker-ready. MP4 generation will run in the dedicated rendering worker rather than blocking the web request.</p></div>}
 <div className="footer">Pipeline: URL → analysis → script → storyboard → stick characters → composition → async render → MP4.</div></form></section></main>;
}
