'use client';

import { FormEvent, useState } from 'react';

type Analysis = { title: string; description: string; features: string[]; hook: string; benefit: string; cta: string; };
type Scene = { order: number; duration: number; purpose: string; narration: string; visual: string; onScreenText: string; };
type Brief = { angle: string; audience: string; hook: string; script: string; cta: string; scenes: Scene[]; };
type PlanScene = Scene & { id: string; characterStyle: string; characterAction?: string };
type Plan = { width: number; height: number; totalDuration: number; scenes: PlanScene[] };

export default function Home() {
  const [url, setUrl] = useState(''); const [format, setFormat] = useState('vertical'); const [template, setTemplate] = useState('product-launch');
  const [status, setStatus] = useState(''); const [analysis, setAnalysis] = useState<Analysis | null>(null); const [brief, setBrief] = useState<Brief | null>(null); const [plan, setPlan] = useState<Plan | null>(null);

  async function analyze(e: FormEvent) { e.preventDefault(); if (!url.trim()) return; setAnalysis(null); setBrief(null); setPlan(null); setStatus('Scraping and analyzing your project…'); try { const res = await fetch('/api/analyze', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({url}) }); const data=await res.json(); if(!res.ok) throw new Error(data.error||'Analysis failed'); setAnalysis(data.analysis); setStatus('Analysis complete.'); } catch(err){setStatus(err instanceof Error?err.message:'Something went wrong.');} }
  async function generateCreative(){ if(!analysis)return; setStatus('Building your marketing angle, script and storyboard…'); try{const res=await fetch('/api/creative',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({analysis,format,template})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Creative generation failed');setBrief(data.brief);setStatus('Creative brief ready.');}catch(err){setStatus(err instanceof Error?err.message:'Creative generation failed.');}}
  async function assemble(){if(!brief)return;setStatus('Preparing video scenes…');try{const res=await fetch('/api/video-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({format,template,scenes:brief.scenes})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Assembly failed');setPlan(data.plan);setStatus('Video assembly plan ready.');}catch(err){setStatus(err instanceof Error?err.message:'Assembly failed.');}}

  return <main className="page"><nav className="nav"><div className="logo">LaunchFrame <span>AI</span></div><div className="badge">MVP • URL → VIDEO</div></nav><section className="hero"><div className="eyebrow">Turn projects into launch content</div><h1>Paste a project.<br/>Get a promo video.</h1><p>LaunchFrame analyzes your website, finds the strongest selling points, writes the script, and prepares a video-ready creative.</p>
    <form className="card" onSubmit={analyze}><label className="label">Project URL</label><div className="row"><input className="input" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://yourproject.com" type="url" required/><button className="primary" disabled={!url.trim()}>Analyze project</button></div>
      <div className="upload">📸 Optional screenshots — upload storage is next. Assets will be available to individual scenes.</div><div className="controls"><select className="select" value={template} onChange={e=>setTemplate(e.target.value)}><option value="product-launch">Product Launch</option><option value="saas-demo">SaaS Demo</option><option value="ai-product">AI Product</option><option value="mobile-app">Mobile App</option></select><select className="select" value={format} onChange={e=>setFormat(e.target.value)}><option value="vertical">Vertical · 9:16</option><option value="horizontal">Horizontal · 16:9</option><option value="square">Square · 1:1</option></select></div>
      {status&&<div className="status">{status}</div>}{analysis&&<div className="results"><div className="panel"><h3>{analysis.title}</h3><p>{analysis.description}</p><ul>{analysis.features.map((f,i)=><li key={i}>{f}</li>)}</ul></div><div className="panel"><h3>Project signals</h3><p><strong>Hook:</strong> {analysis.hook}</p><p><strong>Benefit:</strong> {analysis.benefit}</p><p><strong>CTA:</strong> {analysis.cta}</p></div></div>}
      {analysis&&!brief&&<button type="button" className="primary full" onClick={generateCreative}>Generate script & storyboard →</button>}{brief&&<div className="creative"><div className="panel"><h3>Marketing angle</h3><p>{brief.angle}</p><p><strong>Audience:</strong> {brief.audience}</p><p><strong>Hook:</strong> {brief.hook}</p></div><div className="panel"><h3>Voiceover script</h3><p>{brief.script}</p><p><strong>CTA:</strong> {brief.cta}</p></div><div className="panel storyboard"><h3>Storyboard · {brief.scenes.length} scenes</h3>{brief.scenes.map(scene=><div className="scene" key={scene.order}><div><strong>Scene {scene.order}</strong> · {scene.duration}s · {scene.purpose}</div><p>{scene.narration}</p><small>Visual: {scene.visual}</small><small>On-screen: {scene.onScreenText}</small></div>)}</div><button type="button" className="primary full" onClick={assemble}>Assemble video scenes →</button></div>}
      {plan&&<div className="creative"><div className="panel"><h3>Assembly ready</h3><p>{plan.width} × {plan.height} · {plan.totalDuration}s · {template}</p><p>The renderer will use website assets where available and introduce stick characters only where they improve the explanation.</p></div><div className="panel storyboard"><h3>Character direction</h3>{plan.scenes.map(scene=><div className="scene" key={scene.id}><strong>Scene {scene.order}</strong><p>{scene.characterStyle==='stick'?`Stick character: ${scene.characterAction}`:'No character — focus on product visual.'}</p></div>)}</div><button type="button" className="primary full">Continue to rendering →</button></div>}
      <div className="footer">Pipeline: URL → analysis → script → storyboard → visual assets → stick characters when useful → voiceover → music → async render → MP4.</div>
    </form></section></main>;
}
