export type GeminiCreative={hook:string;benefit:string;cta:string;script:string;scenes:Array<{order:number;duration:number;purpose:string;narration:string;visual:string;onScreenText:string;characterStyle?:'stick'|'none';characterAction?:string}>};
export async function generateGeminiCreative(input:{title:string;description:string;features:string[];format:string;template:string}):Promise<GeminiCreative>{
 const raw=process.env.GEMINI_API_KEY||process.env.GOOGLE_API_KEY;const key=raw?.trim().replace(/^['\"]|['\"]$/g,'');if(!key)throw new Error('GEMINI_API_KEY is not configured.');
 const puppet=/puppet|stick|2d-story/i.test(input.template);
 const style=puppet?'Use an original simple black-line 2D puppet character as a recurring visual storyteller. Give the character clear actions such as presenting, walking, thinking, confused, pointing and celebrating. Keep the character expressive but minimal; do not imitate any named creator or copyrighted character.':'Use product visuals and a stick character only when it improves explanation.';
 const prompt=`Create a concise product promo video plan. Return JSON only matching this schema: {hook,benefit,cta,script,scenes:[{order,duration,purpose,narration,visual,onScreenText,characterStyle,characterAction}]}. Product: ${input.title}. Description: ${input.description}. Features: ${input.features.join(', ')}. Format: ${input.format}. Template: ${input.template}. ${style} Keep narration natural, scenes visually concrete, and make the first 2 seconds attention-grabbing.`;
 const response=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',temperature:0.7}})});
 const payload=await response.json().catch(()=>null);if(!response.ok){const message=payload?.error?.message||`Gemini request failed (${response.status}).`;throw new Error(`Gemini authentication/request failed (${response.status}): ${message}`);}const text=payload?.candidates?.[0]?.content?.parts?.[0]?.text;if(!text)throw new Error('Gemini returned no creative output.');return JSON.parse(text) as GeminiCreative;
}
