import { NextResponse } from 'next/server';
import * as cheerio from 'cheerio';
function clean(value: string | undefined) { return (value || '').replace(/\s+/g, ' ').trim(); }
function absolute(base: URL, value?: string) { if (!value) return null; try { return new URL(value, base).toString(); } catch { return null; } }
function platform(host: string) { const h=host.toLowerCase(); if(h.includes('youtube'))return'YouTube'; if(h.includes('instagram'))return'Instagram'; if(h.includes('tiktok'))return'TikTok'; if(h.includes('twitter')||h.includes('x.com'))return'X'; if(h.includes('linkedin'))return'LinkedIn'; if(h.includes('facebook'))return'Facebook'; return'Web'; }
export async function POST(request: Request) {
 try { const body=await request.json(); const mode=body?.mode==='script'?'script':'url'; const input=typeof body?.input==='string'?body.input.trim():''; if(!input)return NextResponse.json({error:mode==='script'?'Paste a script or brief first.':'A URL is required.'},{status:400});
  if(mode==='script'){const title=clean(body?.title)||'Untitled campaign';const text=input.replace(/\s+/g,' ').trim();const features=text.split(/[.!?]/).map((x:string)=>clean(x)).filter((x:string)=>x.length>25).slice(0,6);return NextResponse.json({analysis:{title,description:text.slice(0,800),features:features.length?features:['User-provided advertising brief'],hook:`Discover ${title}.`,benefit:text.slice(0,180),cta:`Try ${title} today.`},source:{type:'script',platform:'Direct input',url:null,images:[],rawText:text}});}
  const parsed=new URL(input); if(!['http:','https:'].includes(parsed.protocol))throw new Error('Only http and https URLs are supported.'); const response=await fetch(parsed.toString(),{headers:{'User-Agent':'LaunchFrameBot/0.3 (+creative-analysis)'},redirect:'follow',signal:AbortSignal.timeout(12000)}); if(!response.ok)throw new Error(`The source returned HTTP ${response.status}.`);
  const $=cheerio.load(await response.text());$('script,style,noscript').remove(); const title=clean($('meta[property="og:title"]').attr('content'))||clean($('meta[name="twitter:title"]').attr('content'))||clean($('title').text())||parsed.hostname; const description=clean($('meta[property="og:description"]').attr('content'))||clean($('meta[name="description"]').attr('content'))||clean($('main').text()).slice(0,800)||`Discover ${title}.`; const headings=$('h1,h2,h3').map((_,el)=>clean($(el).text())).get().filter(Boolean).slice(0,8); const links=$('a').map((_,el)=>clean($(el).text())).get().filter((x:string)=>x.length>2&&x.length<80); const features=[...new Set([...headings,...links])].slice(0,6); const candidates:string[]=[]; const add=(v?:string)=>{const u=absolute(parsed,v);if(u&&!candidates.includes(u))candidates.push(u);}; add($('meta[property="og:image"]').attr('content'));add($('meta[name="twitter:image"]').attr('content'));$('img').each((_,el)=>add($(el).attr('src')||$(el).attr('data-src')||$(el).attr('data-lazy-src'))); const images=candidates.filter(u=>!/.svg(?:\?|$)/i.test(u)).slice(0,12);
  return NextResponse.json({analysis:{title,description,features:features.length?features:['Clear product experience','Focused user workflow'],hook:`Meet ${title} — a simpler way to get more from your workflow.`,benefit:description.slice(0,180),cta:`Try ${title} today.`},source:{type:'url',platform:platform(parsed.hostname),url:parsed.toString(),images}});
 } catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to analyze this source.'},{status:422});}
}
